# Generated by Django 5.1 on 2024-08-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFarmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='path/to/placeholder.jpg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default='0.00', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=150),
        ),
    ]
