# Generated by Django 5.1 on 2024-08-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFarmapp', '0003_products_created_at_products_updated_at_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
