# Generated by Django 5.1 on 2024-09-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFarmapp', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
